### ISSUE TITLE
aotf: broadcast cycle point globs

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1077]
The cycle points field of the broadcast mutation accepts globs, as a result the validation is incorrect for the default value of `*`:

<img width="407" alt="Screenshot 2022-07-27 at 08 23 34" src="https://user-images.githubusercontent.com/16705946/181186915-61f7742e-ef8e-4a39-9b4a-042fa90b0541.png">

However this value only gets validated when it is edited making it hard for users to tell which field the form error is in.

Suggest validating the form on load and changing the type of the cycle point field to cycle point globs so we can use extended validation rules. Note if doing this the new field will probably need to be registered in `src/utils/aotf`.

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
The broadcast cycle points validation was fixed by https://github.com/cylc/cylc-flow/pull/5007

There shouldn't be any validation errors in the initial state of the form, so I say we close this issue?

**Comment by oliver-sanders** [comment]
Do we still get a validation error if the cycle point is left unchanged?

**Comment by oliver-sanders** [comment]
Closed by https://github.com/cylc/cylc-flow/pull/5007?
